### ISSUE TITLE
Remove final modifier from UriTemplateBuilder

### ISSUE THREAD

**Issue by osvaldopina** [damnhandy/Handy-URI-Templates#46]
Remove final method modifier from UriTemplateBuilder to allow it to be used in EasyMock like frameworks.

**Comment by damnhandy** [comment]
I'm not sure I see the use case for using this library with a framework like EasyMock as opposed to using the API directly. It's light weight and there's no dependencies that you need to mock since you have everything you need. You do have another use case in mind? Otherwise, I'm going to close this issue and reject PR #47

**Comment by damnhandy** [comment]
Since I haven't head back, I'm closing this issue.
